#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

application="$(getApplication)"

foamCleanCase
rm 0/yPlus

runApplication blockMesh
runApllication decomposePar
runApplication renumberMesh -overwrite
runParallel $application

#runApplication reconstructPar

#------------------------------------------------------------------------------
